function(GLFW_HELP)
  message(STATUS "you may try to install glfw like this")
  if(APPLE)
    message(STATUS "brew install glfw")
  elseif(WIN32)
    message(STATUS "brew install glfw")
  elseif(LINUX)
    message(STATUS "brew install glfw")
  endif()
endfunction()
